Update caption of photo
githubschool/soar pull request #20
Opened 2020-12-14 17:39 UTC by agnesbparker

2020-12-14 17:42 UTC, agnesbparker reviewed
ok

2020-12-16 15:08 UTC, ericalloyd requested changes

2020-12-16 15:08 UTC, ericalloyd commented on _slides/04-agnesbparker.md
> +Hello world!
Can we be more specific about who we're addressing?

2020-12-16 15:09 UTC, agnesbparker commented on _slides/04-agnesbparker.md
> +Hello world!
Sure I can do that. I will say Hello Erica!

2020-12-16 15:10 UTC, ericalloyd approved these changes

2020-12-16 15:15 UTC, merged